apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-deploy
  name: api-deploy
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-deploy
  strategy: {}
  template:
    metadata:
      labels:
        app: api-deploy
    spec:
      containers:
      - image: nginx:1.25
        name: nginx
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
status: {}
