apiVersion: v1
kind: Pod
metadata:
  labels:
    run: tolerant-pod
  name: tolerant-pod
spec:
  containers:
  - image: nginx
    name: tolerant-pod
  tolerations:
    - key: env
      operator: "Equal"
      value: "production"
      effect: "NoSchedule"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
