apiVersion: batch/v1
kind: Job
metadata:
  name: db-backup
  namespace: batch
spec:
  completions: 3
  parallelism: 2
  template:
    metadata: {}
    spec:
      containers:
      - command:
        - sh
        - -c
        - echo 'backup done' && sleep 5
        image: busybox
        name: db-backup
        resources: {}
      restartPolicy: Never
status: {}
