apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql-test
type: Opaque
stringData:
  # Default password for testing - CHANGE THIS for production
  mysql-root-password: "TestMySQL@123"
  mysql-database: "testdb"
  mysql-user: "testuser"
  mysql-password: "TestUser@123"
