apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: log-collector
  name: log-collector
  namespace: monitoring 
spec:
  selector:
    matchLabels:
      app: log-collector
  template:
    metadata:
      labels:
        app: log-collector
    spec:
      containers:
      - image: fluentd:latest
        name: fluentd